// -----------------------------------------------------------------------------
// Composition profile
// -----------------------------------------------------------------------------

Profile: RESQStrokeDischargeComposition
Parent: Composition
Id: resq-stroke-discharge-composition
Title: "RESQ Stroke Discharge Patient Summary Composition"
Description: "Composition profile for the RESQ Stroke Discharge Patient Summary document. It assembles the patient, index stroke encounter and clinically relevant registry resources into the FHIR R5 document hierarchy generated by RESQ2FHIR and aligned with the Xt-EHR EHDSDischargeReport logical model."
* ^url = "http://qualityregistry.org/StructureDefinition/resq-stroke-discharge-composition"
* ^name = "RESQStrokeDischargeComposition"
* insert RESQProfileMetadata
* ^fhirVersion = #5.0.0
* ^purpose = "Provides the clinical document entry point for one RES-Q stroke admission, grouping diagnosis, hospital course, treatments, discharge status, medications and follow-up information while keeping each coded fact available as a discrete FHIR resource."
* obeys resq-section-content-or-empty-reason

// Document header
* status 1..1 MS
* status = #final
* status ^short = "Final discharge patient summary"

* type 1..1 MS
* type from RESQStrokeDischargeDocumentTypeVS (required)
* type = LOINC#18842-5 "Discharge summary"
* type ^short = "Discharge summary document type"

* identifier 1..1 MS
* identifier.system 1..1 MS
* identifier.system = "https://stroke.qualityregistry.org/" (exactly)
* identifier.value 1..1 MS
* identifier ^short = "Stable document identifier"

* subject 1..1 MS
* subject only Reference(RESQPatientProfile)
* subject ^short = "Patient discharged after the index stroke admission"

* encounter 0..1 MS
* encounter only Reference(StrokeEncounterProfile)
* encounter ^short = "Index stroke encounter summarized by the document"

* date 1..1 MS
* date ^short = "Date/time the discharge summary was finalized"

* author 1..* MS
* author only Reference(StrokeRegistryOrganizationProfile or Practitioner or RESQPractitionerRoleProfile or Device)
* author ^short = "Authoring organization, clinician, role or system"

* custodian 1..1 MS
* custodian only Reference(StrokeRegistryOrganizationProfile)
* custodian ^short = "Organization responsible for maintaining the document"

* title 1..1 MS
* title = "Stroke Hospital Discharge Summary"
* title ^short = "Human-readable document title"

* language 1..1 MS
* language = #en
* language ^short = "Document language"

* version 1..1 MS
* version = "1"
* version ^short = "Document version emitted by RESQ2FHIR"

* text 1..1 MS
* text ^short = "Narrative rendering of the complete discharge summary"

// Section base rules
* section 1..* MS
* section.code 1..1 MS
* section.code from RESQStrokeDischargeSectionCodeVS (required)
* section.title 1..1 MS
* section.text 1..1 MS
* section.entry MS
* section.emptyReason from http://hl7.org/fhir/ValueSet/list-empty-reason (required)
* section ^short = "EHDS-aligned discharge summary sections"
* section ^definition = "Sections organize narrative, nested document headings and computable entries for the discharge patient summary. When a section is present without entries or nested sections, emptyReason explains why no discrete resources are referenced."


// -------------------------------------------------------
// Root section slicing by section code
// -------------------------------------------------------

* section ^slicing.discriminator[0].type = #pattern
* section ^slicing.discriminator[0].path = "code"
* section ^slicing.rules = #open
* section ^slicing.ordered = true

* section contains
    alerts 1..1 MS and
    allergiesIntolerances 1..1 MS and
    encounterInformation 1..1 MS and
    admissionEvaluation 0..1 MS and
    patientHistory 0..1 MS and
    hospitalCourse 1..1 MS and
    dischargeDetails 1..1 MS and
    medicationSummary 1..1 MS and
    planOfCare 1..1 MS and
    clinicalSynthesis 0..1 MS


// -------------------------------------------------------
// Medical Alerts
// -------------------------------------------------------

* section[alerts].title = "Medical Alerts"
* section[alerts].code = LOINC#75310-3 "Health concerns document"
* section[alerts].emptyReason = http://terminology.hl7.org/CodeSystem/list-empty-reason#notasked "Not Asked"
* section[alerts] ^short = "Required EHDS alerts section; represented as not asked when RES-Q has no alert data"
* section[alerts] ^mapping[0].identity = "EHDSDischargeReport"
* section[alerts] ^mapping[0].map = "body.alerts"


// -------------------------------------------------------
// Allergies and Intolerances
// -------------------------------------------------------

* section[allergiesIntolerances].title = "Allergies and Intolerances"
* section[allergiesIntolerances].code = LOINC#48765-2 "Allergies and adverse reactions document"
* section[allergiesIntolerances].emptyReason = http://terminology.hl7.org/CodeSystem/list-empty-reason#notasked "Not Asked"
* section[allergiesIntolerances] ^short = "Required EHDS allergies section; represented as not asked when RES-Q has no allergy data"
* section[allergiesIntolerances] ^mapping[0].identity = "EHDSDischargeReport"
* section[allergiesIntolerances] ^mapping[0].map = "body.alerts"


// -------------------------------------------------------
// Encounter Information
// -------------------------------------------------------

* section[encounterInformation].title = "Encounter Information"
* section[encounterInformation].code = LOINC#46240-8 "History of hospitalization and outpatient visits"
* section[encounterInformation].entry 1..*
* section[encounterInformation].entry only Reference(StrokeEncounterProfile)
* section[encounterInformation] ^short = "Required encounter context; references the profiled Stroke Encounter"
* section[encounterInformation] ^mapping[0].identity = "EHDSDischargeReport"
* section[encounterInformation] ^mapping[0].map = "body.encounterInformation"


// -------------------------------------------------------
// Admission Evaluation
// -------------------------------------------------------

* section[admissionEvaluation].title = "Admission Evaluation"
* section[admissionEvaluation].code = LOINC#67851-6 "Admission evaluation note"
* section[admissionEvaluation].entry only Reference(StrokeDiagnosisConditionProfile or StrokeRiskFactorConditionProfile or FunctionalScoreObservationProfile or VitalSignObservationProfile or TimingMetricObservationProfile or RESQLocationProfile or HospitalizedLocationProfile)
* section[admissionEvaluation] ^short = "Optional initial clinical status, location and assessment at admission"
* section[admissionEvaluation] ^mapping[0].identity = "EHDSDischargeReport"
* section[admissionEvaluation] ^mapping[0].map = "body.admissionEvaluation"


// -------------------------------------------------------
// Relevant Patient History
// -------------------------------------------------------

* section[patientHistory].title = "Relevant Patient History"
* section[patientHistory].code = LOINC#11329-0 "History of general health narrative"
* section[patientHistory].entry only Reference(PriorMedicationStatementProfile or StrokeRiskFactorConditionProfile or StrokeDiagnosisConditionProfile or PostStrokeComplicationConditionProfile)
* section[patientHistory] ^short = "Optional relevant pre-stroke history, prior medication use and former RES-Q problem list content"
* section[patientHistory] ^mapping[0].identity = "EHDSDischargeReport"
* section[patientHistory] ^mapping[0].map = "body.patientHistory"


// -------------------------------------------------------
// Hospital Course
// -------------------------------------------------------

* section[hospitalCourse].title = "Hospital Course"
* section[hospitalCourse].code = LOINC#8648-8 "Hospital course note"
* section[hospitalCourse].section 1..* MS
* section[hospitalCourse].section ^slicing.discriminator[0].type = #pattern
* section[hospitalCourse].section ^slicing.discriminator[0].path = "code"
* section[hospitalCourse].section ^slicing.rules = #open
* section[hospitalCourse].section ^slicing.ordered = true
* section[hospitalCourse].section contains
    diagnosticSummary 1..1 MS and
    significantProcedures 1..1 MS and
    treatmentTimings 0..1 MS and
    medicalDevices 1..1 MS and
    pharmacotherapy 0..1 MS and
    significantResults 1..1 MS
* section[hospitalCourse] ^short = "Required course-of-encounter container with EHDS child sections"
* section[hospitalCourse] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse] ^mapping[0].map = "body.courseOfEncounter"

* section[hospitalCourse].section[diagnosticSummary].title = "Diagnostic Summary"
* section[hospitalCourse].section[diagnosticSummary].code = LOINC#11535-2 "Hospital discharge diagnosis note"
* section[hospitalCourse].section[diagnosticSummary].entry only Reference(StrokeDiagnosisConditionProfile or StrokeRiskFactorConditionProfile or PostStrokeComplicationConditionProfile or SpecificFindingObservationProfile or StrokeImagingDiagnosticReportProfile or MechanicalThrombectomyDiagnosticReportProfile)
* section[hospitalCourse].section[diagnosticSummary] ^short = "Required final diagnosis and supporting diagnostic findings"
* section[hospitalCourse].section[diagnosticSummary] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[diagnosticSummary] ^mapping[0].map = "body.courseOfEncounter.diagnosticSummary"

* section[hospitalCourse].section[significantProcedures].title = "Significant Procedures"
* section[hospitalCourse].section[significantProcedures].code = LOINC#10185-7 "Hospital discharge procedure note"
* section[hospitalCourse].section[significantProcedures].entry only Reference(StrokeImagingProcedureProfile or StrokeCarotidImagingProcedureProfile or StrokeCarotidEndarterectomyProcedureProfile or StrokeMechanicalProcedureProfile or StrokeSwallowProcedureProfile or StrokeVTEProcedureProfile or StrokeTreatmentProcedureProfile)
* section[hospitalCourse].section[significantProcedures] ^short = "Required clinically significant procedures performed or considered"
* section[hospitalCourse].section[significantProcedures] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[significantProcedures] ^mapping[0].map = "body.courseOfEncounter.procedures"

* section[hospitalCourse].section[treatmentTimings].title = "Treatment Timings"
* section[hospitalCourse].section[treatmentTimings].code = StrokeDischargeSummarySectionCS#treatment-timings "Treatment Timings"
* section[hospitalCourse].section[treatmentTimings].entry only Reference(TimingMetricObservationProfile)
* section[hospitalCourse].section[treatmentTimings] ^short = "Optional stroke-specific RES-Q timing metrics D2N, D2G and D2D"
* section[hospitalCourse].section[treatmentTimings] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[treatmentTimings] ^mapping[0].map = "body.courseOfEncounter"

* section[hospitalCourse].section[medicalDevices].title = "Medical Devices and Implants"
* section[hospitalCourse].section[medicalDevices].code = SCT#1184586001 "Medical device document section"
* section[hospitalCourse].section[medicalDevices].emptyReason = http://terminology.hl7.org/CodeSystem/list-empty-reason#notasked "Not Asked"
* section[hospitalCourse].section[medicalDevices] ^short = "Required EHDS medical devices section; represented as not asked when RES-Q has no device data"
* section[hospitalCourse].section[medicalDevices] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[medicalDevices] ^mapping[0].map = "body.courseOfEncounter.medicalDevicesAndImplants"

* section[hospitalCourse].section[pharmacotherapy].title = "Pharmacotherapy During Encounter"
* section[hospitalCourse].section[pharmacotherapy].code = LOINC#87232-5 "Medication administration brief"
* section[hospitalCourse].section[pharmacotherapy].entry only Reference(StrokeMedicationAdministrationProfile or ParacetamolOnFeverMedicationAdministrationProfile or InsulinOnHyperglycemiaMedicationAdministrationProfile or NimodipineMedicationAdministrationProfile or AnticoagulantReversalMedicationAdministrationProfile)
* section[hospitalCourse].section[pharmacotherapy] ^short = "Optional medication administrations during acute or post-acute stroke care"
* section[hospitalCourse].section[pharmacotherapy] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[pharmacotherapy] ^mapping[0].map = "body.courseOfEncounter.pharmacotherapy"

* section[hospitalCourse].section[significantResults].title = "Significant Test Results"
* section[hospitalCourse].section[significantResults].code = LOINC#30954-2 "Relevant diagnostic tests and laboratory data note"
* section[hospitalCourse].section[significantResults].entry only Reference(SpecificFindingObservationProfile or AnaliticsObservationProfile or FeverObservationProfile or HyperglycemiaObservationProfile or GlucoseGE10ObservationProfile or HighestHyperglycemiaValueObservationProfile or SystolicBloodPressureHighestValueObservationProfile or StrokeImagingDiagnosticReportProfile or MechanicalThrombectomyDiagnosticReportProfile)
* section[hospitalCourse].section[significantResults] ^short = "Required relevant diagnostic, imaging and laboratory results"
* section[hospitalCourse].section[significantResults] ^mapping[0].identity = "EHDSDischargeReport"
* section[hospitalCourse].section[significantResults] ^mapping[0].map = "body.courseOfEncounter.testResults[x]"


// -------------------------------------------------------
// Discharge Details
// -------------------------------------------------------

* section[dischargeDetails].title = "Discharge Details"
* section[dischargeDetails].code = LOINC#8650-4 "Hospital discharge disposition note"
* section[dischargeDetails].entry 1..*
* section[dischargeDetails].entry only Reference(StrokeEncounterProfile)
* section[dischargeDetails].section 1..* MS
* section[dischargeDetails].section ^slicing.discriminator[0].type = #pattern
* section[dischargeDetails].section ^slicing.discriminator[0].path = "code"
* section[dischargeDetails].section ^slicing.rules = #open
* section[dischargeDetails].section ^slicing.ordered = true
* section[dischargeDetails].section contains
    vitalSigns 1..1 MS and
    anthropometry 1..1 MS and
    physicalExamination 1..1 MS and
    functionalStatus 1..1 MS
* section[dischargeDetails] ^short = "Required discharge destination, disposition and objective discharge findings"
* section[dischargeDetails] ^mapping[0].identity = "EHDSDischargeReport"
* section[dischargeDetails] ^mapping[0].map = "body.dischargeDetails"

* section[dischargeDetails].section[vitalSigns].title = "Vital Signs at Discharge"
* section[dischargeDetails].section[vitalSigns].code = LOINC#8716-3 "Vital signs note"
* section[dischargeDetails].section[vitalSigns].entry only Reference(VitalSignObservationProfile or SystolicBloodPressureHighestValueObservationProfile)
* section[dischargeDetails].section[vitalSigns] ^short = "Required vital signs relevant to discharge status"
* section[dischargeDetails].section[vitalSigns] ^mapping[0].identity = "EHDSDischargeReport"
* section[dischargeDetails].section[vitalSigns] ^mapping[0].map = "body.dischargeDetails.objectiveFindings"

* section[dischargeDetails].section[anthropometry].title = "Anthropometric Measurements"
* section[dischargeDetails].section[anthropometry].code = SCT#248326004 "Anthropometric measure"
* section[dischargeDetails].section[anthropometry].emptyReason = http://terminology.hl7.org/CodeSystem/list-empty-reason#notasked "Not Asked"
* section[dischargeDetails].section[anthropometry] ^short = "Required anthropometric measurements section; represented as not asked when RES-Q has no anthropometry data"
* section[dischargeDetails].section[anthropometry] ^mapping[0].identity = "EHDSDischargeReport"
* section[dischargeDetails].section[anthropometry] ^mapping[0].map = "body.dischargeDetails.objectiveFindings"

* section[dischargeDetails].section[physicalExamination].title = "Physical Examination at Discharge"
* section[dischargeDetails].section[physicalExamination].code = LOINC#29545-1 "Physical findings"
* section[dischargeDetails].section[physicalExamination].emptyReason = http://terminology.hl7.org/CodeSystem/list-empty-reason#notasked "Not Asked"
* section[dischargeDetails].section[physicalExamination] ^short = "Required physical examination section; represented as not asked when RES-Q has no physical examination data"
* section[dischargeDetails].section[physicalExamination] ^mapping[0].identity = "EHDSDischargeReport"
* section[dischargeDetails].section[physicalExamination] ^mapping[0].map = "body.dischargeDetails.objectiveFindings"

* section[dischargeDetails].section[functionalStatus].title = "Functional Status at Discharge"
* section[dischargeDetails].section[functionalStatus].code = LOINC#47420-5 "Functional status assessment note"
* section[dischargeDetails].section[functionalStatus].entry only Reference(FunctionalScoreObservationProfile or GlasgowComaScoreObservationProfile or GlasgowComaScaleObservationProfile or PatientVentilatedObservationProfile or QuestionnaireResponse)
* section[dischargeDetails].section[functionalStatus] ^short = "Required functional and neurological status at discharge"
* section[dischargeDetails].section[functionalStatus] ^mapping[0].identity = "EHDSDischargeReport"
* section[dischargeDetails].section[functionalStatus] ^mapping[0].map = "body.dischargeDetails.functionalStatus[x]"


// -------------------------------------------------------
// Medication Summary at Discharge
// -------------------------------------------------------

* section[medicationSummary].title = "Medication Summary at Discharge"
* section[medicationSummary].code = LOINC#75311-1 "Discharge medications note"
* section[medicationSummary].entry only Reference(DischargeMedicationRequestProfile or NoAnticoagulantDischargeReasonObservationProfile)
* section[medicationSummary] ^short = "Required medication orders or omission reasons at discharge"
* section[medicationSummary] ^mapping[0].identity = "EHDSDischargeReport"
* section[medicationSummary] ^mapping[0].map = "body.medicationSummary"


// -------------------------------------------------------
// Plan of Care and Follow-up
// -------------------------------------------------------

* section[planOfCare].title = "Plan of Care and Follow-up"
* section[planOfCare].code = LOINC#18776-5 "Plan of care note"
* section[planOfCare].entry only Reference(FollowUpAppointmentProfile or ThreeMonthCommunicationProfile or AppointmentManagementObservationProfile or ThreeMonthContactModeObservationProfile or StrokeTreatmentProcedureProfile or CarePlan or ServiceRequest)
* section[planOfCare] ^short = "Required follow-up plan, scheduled contact and continuing care recommendations"
* section[planOfCare] ^mapping[0].identity = "EHDSDischargeReport"
* section[planOfCare] ^mapping[0].map = "body.carePlan"


// -------------------------------------------------------
// Clinical Synthesis
// -------------------------------------------------------

* section[clinicalSynthesis].title = "Clinical Synthesis"
* section[clinicalSynthesis].code = SCT#866144008 "Encounter note"
* section[clinicalSynthesis].entry 0..0
* section[clinicalSynthesis] ^short = "Optional deterministic clinical synthesis narrative generated from already modeled FHIR resources"
* section[clinicalSynthesis] ^mapping[0].identity = "EHDSDischargeReport"
* section[clinicalSynthesis] ^mapping[0].map = "body.clinicalSynthesis"

Invariant: resq-section-content-or-empty-reason
Description: "Every section in the RESQ discharge patient summary should either reference at least one entry, contain child sections, state why no entry is available, or be the narrative-only Clinical Synthesis section."
Severity: #warning
Expression: "section.repeat(section).all(entry.exists() or section.exists() or emptyReason.exists() or (code.coding.where(system = 'http://snomed.info/sct' and code = '866144008').exists() and text.exists()))"
